import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#474747',
        'primary-container': '#d4d4d4',
        'primary': '#ffffff',
        'secondary-fixed': '#c8c6c6',
        'on-primary-fixed-variant': '#e2e2e2',
        'on-secondary-container': '#e4e2e1',
        'on-tertiary-container': '#000000',
        'inverse-primary': '#5d5f5f',
        'surface-container-high': '#2a2a2a',
        'primary-fixed-dim': '#454747',
        'inverse-on-surface': '#313030',
        'surface-variant': '#353534',
        'tertiary-container': '#929090',
        'on-surface-variant': '#c6c6c6',
        'surface-bright': '#3a3939',
        'on-background': '#e5e2e1',
        'background': '#121212',
        'on-tertiary': '#1c1b1b',
        'surface-dim': '#121212',
        'outline': '#919191',
        'secondary-fixed-dim': '#acabab',
        'on-error': '#690005',
        'surface-container': '#201f1f',
        'primary-fixed': '#5d5f5f',
        'surface': '#121212',
        'on-primary-fixed': '#ffffff',
        'secondary': '#c8c6c6',
        'surface-tint': '#c6c6c7',
        'surface-container-lowest': '#0e0e0e',
        'on-secondary': '#1b1c1c',
        'tertiary-fixed': '#5f5e5e',
        'tertiary-fixed-dim': '#474746',
        'on-primary-container': '#000000',
        'error-container': '#93000a',
        'inverse-surface': '#e5e2e1',
        'error': '#ffb4ab',
        'on-tertiary-fixed': '#ffffff',
        'secondary-container': '#474747',
        'on-secondary-fixed-variant': '#3b3b3b',
        'on-tertiary-fixed-variant': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'surface-container-low': '#1c1b1b',
        'on-primary': '#1a1c1c',
        'tertiary': '#e5e2e1',
        'surface-container-highest': '#353534',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed': '#1b1c1c',
      },
      maxWidth: {
        '8xl': '88rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Space Grotesk', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
} satisfies Config